workflow updates

diff --git a/.github/workflows/apps-tests.yaml b/.github/workflows/apps-tests.yaml
--- a/.github/workflows/apps-tests.yaml
+++ b/.github/workflows/apps-tests.yaml
@@ -46,7 +46,7 @@ jobs:
       - name: Install uv
         uses: astral-sh/setup-uv@v5
         with:
-          version: "0.4.25"
+          version: "0.6.10"
 
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v5
@@ -70,14 +70,18 @@ jobs:
 
       - name: Run the test
         run: |
+          set +e # Disable exit on error
+
           chmod +x ./run.sh
           export SYFTBOX_CLIENT_CONFIG_PATH="$(pwd)/config.json"
           timeout 10s sh ./run.sh
+
+          set -e  # Re-enable exit on error
+
           exit_code=$?
           if [ $exit_code -eq 124 ]; then
             echo "run.sh is running long as expected; marking step as success."
             exit 0
           else
-            echo "run.sh exited with code $exit_code."
             exit $exit_code
           fi
