apps test exit code fix

diff --git a/.github/workflows/apps-tests.yaml b/.github/workflows/apps-tests.yaml
--- a/.github/workflows/apps-tests.yaml
+++ b/.github/workflows/apps-tests.yaml
@@ -70,18 +70,19 @@ jobs:
 
       - name: Run the test
         run: |
-          set +e # Disable exit on error
+          set +x
 
-          chmod +x ./run.sh
-          export SYFTBOX_CLIENT_CONFIG_PATH="$(pwd)/config.json"
           timeout 10s sh ./run.sh
 
-          set -e  # Re-enable exit on error
-
           exit_code=$?
+          echo "Exit code: $exit_code"
+
+          set -e
+
           if [ $exit_code -eq 124 ]; then
-            echo "run.sh is running long as expected; marking step as success."
-            exit 0
+              echo "run.sh is running long as expected; marking step as success."
+              exit 0
           else
-            exit $exit_code
+              echo "run.sh error; marking step as failure."
+              exit $exit_code
           fi
